const localizedCatalogFields = ["separator","app","repository","documents","settings","designStudio","help","history","overview","summary","detail","workflow","maintenance","security","actions","lessons","context","health","source","command","field","state","risk","mock","title","description","status","review","value","current","next","ready","missing","unknown","item","page"];

const localizedCatalogRows = {
  "en": [" - ","App","Repository","Documents","Settings","Design Studio","Help","Update History","Overview","Summary","Detail","Development Workflow","Maintenance Sync","Safety","Actions","Lessons","Context","Health","Source","Command","Field","State","Risk","View","Title","Description","Status","Review","Value","Current","Next","Ready","Missing","Unknown","Item","Page"],
  "ja": [" - ","アプリ","リポジトリ","ドキュメント","設定","デザインスタジオ","ヘルプ","更新履歴","概要","概要","詳細","開発ワークフロー","保守・同期","安全確認","操作","レッスン","コンテキスト","状態","情報元","コマンド","項目","状態","リスク","表示","タイトル","説明","状態","確認","値","現在","次","進行可能","必要情報不足","不明","項目","ページ"],
  "ko": [" - ","앱","저장소","문서","설정","디자인 스튜디오","도움말","업데이트 기록","개요","요약","세부 정보","개발 워크플로","유지보수 동기화","안전 확인","작업","레슨","컨텍스트","상태","출처","명령","필드","상태","위험","표시","제목","설명","상태","검토","값","현재","다음","준비됨","누락","알 수 없음","항목","페이지"],
  "zh-CN": [" - ","应用","代码库","文档","设置","设计工作室","帮助","更新历史","概览","摘要","详细信息","开发工作流","维护同步","安全检查","操作","课程","上下文","状态","来源","命令","字段","状态","风险","显示","标题","说明","状态","检查","值","当前","下一步","就绪","缺失","未知","项目","页面"],
  "zh-TW": [" - ","應用","儲存庫","文件","設定","設計工作室","說明","更新記錄","概覽","摘要","詳細資訊","開發工作流程","維護同步","安全檢查","操作","課程","情境","狀態","來源","命令","欄位","狀態","風險","顯示","標題","說明","狀態","檢視","值","目前","下一步","就緒","缺少","未知","項目","頁面"],
  "es": [" - ","Aplicación","Repositorio","Documentos","Configuración","Estudio de diseño","Ayuda","Historial","Resumen","Resumen","Detalle","Flujo de desarrollo","Sincronización de mantenimiento","Seguridad","Acciones","Lecciones","Contexto","Estado","Fuente","Comando","Campo","Estado","Riesgo","Vista","Título","Descripción","Estado","Revisión","Valor","Actual","Siguiente","Listo","Faltante","Desconocido","Elemento","Página"],
  "pt-BR": [" - ","Aplicativo","Repositório","Documentos","Configurações","Estúdio de design","Ajuda","Histórico","Visão geral","Resumo","Detalhe","Fluxo de desenvolvimento","Sincronização de manutenção","Segurança","Ações","Lições","Contexto","Estado","Fonte","Comando","Campo","Estado","Risco","Visualização","Título","Descrição","Estado","Revisão","Valor","Atual","Próximo","Pronto","Ausente","Desconhecido","Item","Página"],
  "fr": [" - ","Application","Dépôt","Documents","Paramètres","Studio de design","Aide","Historique","Vue d'ensemble","Résumé","Détail","Flux de développement","Synchronisation de maintenance","Sécurité","Actions","Leçons","Contexte","État","Source","Commande","Champ","État","Risque","Affichage","Titre","Description","État","Revue","Valeur","Actuel","Suivant","Prêt","Manquant","Inconnu","Élément","Page"],
  "de": [" - ","App","Repository","Dokumente","Einstellungen","Design Studio","Hilfe","Verlauf","Übersicht","Zusammenfassung","Detail","Entwicklungsworkflow","Wartungssynchronisierung","Sicherheit","Aktionen","Lektionen","Kontext","Status","Quelle","Befehl","Feld","Status","Risiko","Ansicht","Titel","Beschreibung","Status","Prüfung","Wert","Aktuell","Weiter","Bereit","Fehlt","Unbekannt","Eintrag","Seite"],
  "id": [" - ","Aplikasi","Repositori","Dokumen","Pengaturan","Studio desain","Bantuan","Riwayat","Ringkasan","Ringkasan","Detail","Alur kerja pengembangan","Sinkronisasi pemeliharaan","Keamanan","Tindakan","Pelajaran","Konteks","Status","Sumber","Perintah","Kolom","Status","Risiko","Tampilan","Judul","Deskripsi","Status","Tinjauan","Nilai","Saat ini","Berikutnya","Siap","Tidak ada","Tidak diketahui","Item","Halaman"],
  "vi": [" - ","Ứng dụng","Kho mã","Tài liệu","Cài đặt","Xưởng thiết kế","Trợ giúp","Lịch sử","Tổng quan","Tóm tắt","Chi tiết","Quy trình phát triển","Đồng bộ bảo trì","An toàn","Hành động","Bài học","Ngữ cảnh","Trạng thái","Nguồn","Lệnh","Trường","Trạng thái","Rủi ro","Hiển thị","Tiêu đề","Mô tả","Trạng thái","Rà soát","Giá trị","Hiện tại","Tiếp theo","Sẵn sàng","Thiếu","Không rõ","Mục","Trang"],
  "th": [" - ","แอป","ที่เก็บโค้ด","เอกสาร","การตั้งค่า","สตูดิโอออกแบบ","ช่วยเหลือ","ประวัติ","ภาพรวม","สรุป","รายละเอียด","เวิร์กโฟลว์พัฒนา","ซิงค์บำรุงรักษา","ความปลอดภัย","การทำงาน","บทเรียน","บริบท","สถานะ","แหล่งข้อมูล","คำสั่ง","ฟิลด์","สถานะ","ความเสี่ยง","มุมมอง","ชื่อ","คำอธิบาย","สถานะ","ตรวจสอบ","ค่า","ปัจจุบัน","ถัดไป","พร้อม","ขาด","ไม่ทราบ","รายการ","หน้า"],
  "hi": [" - ","ऐप","रिपॉजिटरी","दस्तावेज़","सेटिंग्स","डिज़ाइन स्टूडियो","सहायता","इतिहास","सारांश","सारांश","विवरण","विकास वर्कफ़्लो","रखरखाव सिंक","सुरक्षा","कार्रवाई","पाठ","संदर्भ","स्थिति","स्रोत","कमांड","फ़ील्ड","स्थिति","जोखिम","दृश्य","शीर्षक","विवरण","स्थिति","समीक्षा","मान","वर्तमान","अगला","तैयार","अनुपस्थित","अज्ञात","आइटम","पृष्ठ"],
  "ar": [" - ","التطبيق","المستودع","المستندات","الإعدادات","استوديو التصميم","المساعدة","سجل التحديث","نظرة عامة","ملخص","تفاصيل","سير عمل التطوير","مزامنة الصيانة","الأمان","الإجراءات","الدروس","السياق","الحالة","المصدر","الأمر","الحقل","الحالة","المخاطر","العرض","العنوان","الوصف","الحالة","المراجعة","القيمة","الحالي","التالي","جاهز","مفقود","غير معروف","العنصر","الصفحة"],
};

export const localizedCatalog = Object.freeze(Object.fromEntries(
  Object.entries(localizedCatalogRows).map(([code, values]) => [
    code,
    Object.freeze(Object.fromEntries(localizedCatalogFields.map((field, index) => [field, values[index]]))),
  ]),
));
