#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA="$ROOT/docs/workflow/DASHBOARD_DATA_SCHEMA.tsv"
missing=0

report() {
  printf '%s\n' "$1" >&2
  missing=1
}

require_path() {
  local path="$1"
  if ! awk -F '\t' -v path="$path" '$1 !~ /^#/ && $2 == path { found = 1 } END { exit found ? 0 : 1 }' "$SCHEMA"; then
    report "missing dashboard schema path: $path"
  fi
}

require_enum_contains() {
  local path="$1"
  local token="$2"
  if ! awk -F '\t' -v path="$path" -v token="$token" '
    $1 !~ /^#/ && $2 == path {
      split($5, values, /\|/)
      for (i in values) {
        if (values[i] == token) found = 1
      }
    }
    END { exit found ? 0 : 1 }
  ' "$SCHEMA"; then
    report "missing enum token for $path: $token"
  fi
}

require_implemented_status() {
  local path="$1"
  if ! awk -F '\t' -v path="$path" '
    $1 !~ /^#/ && $2 == path && $3 == "implemented" { found = 1 }
    END { exit found ? 0 : 1 }
  ' "$SCHEMA"; then
    report "dashboard schema path is not implemented: $path"
  fi
}

[[ -f "$SCHEMA" ]] || {
  printf 'missing dashboard schema: %s\n' "$SCHEMA" >&2
  exit 1
}

awk -F '\t' '
  $1 ~ /^#/ { next }
  NF != 7 {
    printf "invalid dashboard schema column count on line %d: %d\n", NR, NF > "/dev/stderr"
    invalid = 1
    next
  }
  {
    for (i = 1; i <= 7; i++) {
      if ($i == "") {
        printf "empty dashboard schema field on line %d column %d\n", NR, i > "/dev/stderr"
        invalid = 1
      }
    }
    if ($3 != "implemented" && $3 != "planned") {
      printf "unexpected dashboard schema status on line %d: %s\n", NR, $3 > "/dev/stderr"
      invalid = 1
    }
    if (seen[$2]++) {
      printf "duplicate dashboard schema path on line %d: %s\n", NR, $2 > "/dev/stderr"
      invalid = 1
    }
    if ($2 == "git_workflow.status" || $2 == "security.status") {
      printf "unsafe aggregate status path on line %d: %s\n", NR, $2 > "/dev/stderr"
      invalid = 1
    }
  }
  END { exit invalid ? 1 : 0 }
' "$SCHEMA" || missing=1

required_paths=(
  "schema_version"
  "generated_at"
  "snapshot_id"
  "content_hash"
  "source_files"
  "source_commands"
  "warnings"
  "selected_context"
  "selected_context.menu_id"
  "selected_context.workflow_context"
  "selected_context.target_repository"
  "selected_context.target_repository.repo_id"
  "selected_context.target_repository.name"
  "selected_context.target_repository.path_state"
  "selected_context.target_repository.selection_state"
  "selected_context.product_type"
  "selected_context.current_step_id"
  "selected_context.current_step_label"
  "selected_context.current_step_index"
  "selected_context.current_step_total"
  "selected_context.updated_at"
  "selected_context.git_status"
  "selected_context.ci_status"
  "selected_context.security_status"
  "selected_context.evidence_status"
  "selected_context.next_safe_action"
  "selected_context.blockers"
  "available_contexts[]"
  "available_contexts[].menu_id"
  "available_contexts[].workflow_context"
  "available_contexts[].target_repository_name"
  "available_contexts[].status"
  "available_contexts[].selectable"
  "available_contexts[].disabled_reason_key"
  "available_contexts[].disabled_detail"
  "available_contexts[].required_next_action"
  "repository_selection"
  "repository_selection.status"
  "repository_selection.menu_id"
  "repository_selection.workflow_context"
  "repository_selection.current_repo_id"
  "repository_selection.current_repository_name"
  "repository_selection.selection_state"
  "repository_selection.registry_file"
  "repository_selection.selection_file"
  "repository_selection.options[]"
  "repository_selection.options[].repo_id"
  "repository_selection.options[].display_name"
  "repository_selection.options[].primary_menu_id"
  "repository_selection.options[].allowed_contexts[]"
  "repository_selection.options[].product_type"
  "repository_selection.options[].registration_source"
  "repository_selection.options[].path_state"
  "repository_selection.options[].git_state"
  "repository_selection.options[].status"
  "repository_selection.options[].selectable"
  "repository_selection.options[].selected"
  "repository_selection.options[].disabled_reason_key"
  "repository_selection.options[].disabled_detail"
  "repository_selection.options[].select_command"
  "partial_failures[].source"
  "partial_failures[].status"
  "partial_failures[].reason"
  "partial_failures[].required_command"
  "summary.mode"
  "summary.workflow_language"
  "summary.display_locale"
  "summary.ui_locale"
  "summary.ui_direction"
  "summary.next_safe_action"
  "summary.primary_action.title"
  "summary.primary_action.description"
  "summary.primary_action.target"
  "summary.primary_action.expected_result"
  "summary.primary_action.risk_level"
  "summary.primary_action.status"
  "summary.primary_action.source"
  "summary.category_metrics.overview"
  "summary.category_metrics.lessons"
  "summary.category_metrics.workflow"
  "summary.category_metrics.maintenance"
  "summary.category_metrics.security"
  "summary.category_metrics.*.total"
  "summary.category_metrics.*.healthy"
  "summary.category_metrics.*.warning"
  "summary.category_metrics.*.problem"
  "summary.category_metrics.*.percent"
  "summary.category_metrics.*.unit"
  "summary.category_metrics.*.status"
  "summary.guidance_items[].surface"
  "summary.guidance_items[].audience"
  "summary.guidance_items[].priority"
  "summary.guidance_items[].message"
  "summary.guidance_items[].related_command"
  "summary.blocking_items[].source"
  "summary.blocking_items[].status"
  "summary.blocking_items[].reason"
  "summary.blocking_items[].required_command"
  "summary.manual_followups[].source"
  "summary.manual_followups[].status"
  "summary.manual_followups[].reason"
  "summary.manual_followups[].required_command"
  "live_status"
  "live_status.schema_version"
  "live_status.generated_at"
  "live_status.menu_id"
  "live_status.workflow_context"
  "live_status.target_repository"
  "live_status.target_repository.repo_id"
  "live_status.target_repository.name"
  "live_status.target_repository.path_state"
  "live_status.target_repository.git_state"
  "live_status.target_repository.git_usage_mode"
  "live_status.target_repository.selection_state"
  "live_status.repository_state"
  "live_status.repository_state.branch"
  "live_status.repository_state.head"
  "live_status.repository_state.upstream"
  "live_status.repository_state.dirty_count"
  "live_status.repository_state.untracked_count"
  "live_status.repository_state.ahead"
  "live_status.repository_state.behind"
  "live_status.git_activity"
  "live_status.git_activity.operations[]"
  "live_status.git_activity.operations[].id"
  "live_status.git_activity.operations[].status"
  "live_status.git_activity.operations[].detail_code"
  "live_status.test_activity"
  "live_status.test_activity.running_count"
  "live_status.test_activity.recent[]"
  "live_status.test_activity.recent[].id"
  "live_status.test_activity.recent[].status"
  "live_status.runtime_activity"
  "live_status.runtime_activity.observed_at"
  "live_status.runtime_activity.process_count"
  "live_status.runtime_activity.redaction_status"
  "live_status.runtime_activity.items[]"
  "live_status.runtime_activity.items[].command_id"
  "live_status.runtime_activity.items[].category"
  "live_status.runtime_activity.items[].pid_hash"
  "live_status.runtime_activity.items[].state"
  "live_status.runtime_activity.items[].elapsed_ms"
  "live_status.runtime_activity.items[].cwd_role"
  "live_status.runtime_activity.items[].argv_preview"
  "live_status.runtime_activity.items[].redaction_status"
  "live_status.active_operations"
  "live_status.active_operations.observed_at"
  "live_status.active_operations.process_count"
  "live_status.active_operations.redaction_status"
  "live_status.active_operations.items[]"
  "live_status.active_operations.items[].command_id"
  "live_status.active_operations.items[].category"
  "live_status.active_operations.items[].pid_hash"
  "live_status.active_operations.items[].state"
  "live_status.active_operations.items[].elapsed_ms"
  "live_status.active_operations.items[].cwd_role"
  "live_status.active_operations.items[].argv_preview"
  "live_status.active_operations.items[].redaction_status"
  "live_status.agent_sessions[]"
  "live_status.agent_sessions[].session_id"
  "live_status.agent_sessions[].status"
  "live_status.agent_sessions[].repo_id"
  "live_status.agent_assignments[]"
  "live_status.agent_assignments[].assignment_id"
  "live_status.agent_assignments[].session_id"
  "live_status.agent_assignments[].repo_id"
  "live_status.tool_calls[]"
  "live_status.tool_calls[].tool_call_id"
  "live_status.tool_calls[].command_id"
  "live_status.tool_calls[].dry_run"
  "live_status.operation_events[]"
  "live_status.operation_events[].event_id"
  "live_status.operation_events[].event_type"
  "live_status.operation_events[].status"
  "live_status.operation_events[].redaction_status"
  "live_status.checks"
  "live_status.checks.local_tests"
  "live_status.checks.git_sync"
  "live_status.checks.ci"
  "live_status.checks.security"
  "live_status.checks.*.status"
  "live_status.checks.*.observed_at"
  "live_status.checks.*.detail_code"
  "live_status.checks.*.source_id"
  "live_status.checks.*.summary"
  "live_status.checks.*.reason"
  "live_status.checks.*.next_action"
  "live_status.checks.*.detail_page"
  "live_status.checks.*.freshness_state"
  "live_status.checks.*.authority"
  "live_status.checks.*.risk_level"
  "live_status.checks.*.required_command"
  "live_status.checks.*.current_item_id"
  "live_status.checks.*.items[]"
  "live_status.checks.*.items[].source_id"
  "live_status.checks.*.items[].category"
  "live_status.checks.*.items[].kind"
  "live_status.checks.*.items[].status"
  "live_status.checks.*.items[].observed_at"
  "live_status.checks.*.items[].freshness_state"
  "live_status.checks.*.items[].authority"
  "live_status.checks.*.items[].summary"
  "live_status.checks.*.items[].source_artifacts"
  "live_status.checks.*.items[].next_command"
  "live_status.checks.*.items[].blocker_count"
  "live_status.checks.ci.workflow_name"
  "live_status.checks.ci.run_status"
  "live_status.checks.ci.conclusion"
  "live_status.checks.ci.run_id"
  "live_status.checks.ci.run_url"
  "live_status.checks.ci.repository_head"
  "live_status.checks.ci.run_head_sha"
  "live_status.checks.ci.run_head_branch"
  "live_status.checks.ci.head_match_status"
  "lessons.step_1_7"
  "lessons.step_1_7.points"
  "lessons.step_1_7.warnings"
  "lessons.step_1_7.next_learning_action"
  "lessons.step_1_14"
  "lessons.step_1_14.points"
  "lessons.step_1_14.warnings"
  "lessons.step_1_14.next_learning_action"
  "lessons.advanced"
  "lessons.advanced.points"
  "lessons.advanced.warnings"
  "lessons.advanced.next_learning_action"
  "development.product_repository.status"
  "development.documents.status"
  "documents"
  "documents.status"
  "documents.groups[]"
  "documents.groups[].id"
  "documents.groups[].label_key"
  "documents.groups[].description_key"
  "documents.groups[].order"
  "documents.catalog[]"
  "documents.catalog[].id"
  "documents.catalog[].group_id"
  "documents.catalog[].role_id"
  "documents.catalog[].path"
  "documents.catalog[].status"
  "documents.catalog[].status_source"
  "documents.catalog[].audience"
  "documents.catalog[].order"
  "documents.catalog[].related_page"
  "documents.related_commands[]"
  "documents.related_commands[].id"
  "documents.related_commands[].label_key"
  "documents.related_commands[].description_key"
  "documents.related_commands[].command"
  "documents.related_commands[].order"
  "documents.brief_cards[]"
  "documents.brief_cards[].id"
  "documents.brief_cards[].menu_id"
  "documents.brief_cards[].workflow_context"
  "documents.brief_cards[].repo_id"
  "documents.brief_cards[].document_role"
  "documents.brief_cards[].freshness_state"
  "settings"
  "settings.status"
  "settings.groups[]"
  "settings.groups[].id"
  "settings.groups[].label_key"
  "settings.groups[].description_key"
  "settings.groups[].status"
  "settings.groups[].order"
  "settings.items[]"
  "settings.items[].id"
  "settings.items[].group_id"
  "settings.items[].scope"
  "settings.items[].label_key"
  "settings.items[].description_key"
  "settings.items[].current_value"
  "settings.items[].current_label"
  "settings.items[].status"
  "settings.items[].source_file"
  "settings.items[].allowed_values[]"
  "settings.items[].editable"
  "settings.items[].reviewable"
  "settings.items[].risk_level"
  "settings.items[].requires_confirmation"
  "settings.items[].disabled_reason_key"
  "settings.items[].related_page"
  "settings.items[].update_action_id"
  "settings.items[].consistency"
  "settings.items[].consistency.status"
  "settings.items[].consistency.severity"
  "settings.items[].consistency.reason_code"
  "settings.items[].consistency.reason_key"
  "settings.items[].consistency.next_action_key"
  "settings.items[].consistency.effective_mode"
  "settings.items[].consistency.affected_setting_ids[]"
  "settings.items[].review"
  "settings.items[].review.impact_key"
  "settings.items[].review.target_file"
  "settings.items[].review.validation_status"
  "settings.items[].review.update_preview_key"
  "development.git_sync_status"
  "development.ci_status"
  "development.git_operations[]"
  "development.git_operations[].id"
  "development.git_operations[].label"
  "development.git_operations[].status"
  "development.git_operations[].mode"
  "development.git_operations[].detail"
  "development.repository_changes"
  "development.repository_changes.status"
  "development.repository_changes.observed_at"
  "development.repository_changes.path_state"
  "development.repository_changes.git_state"
  "development.repository_changes.branch"
  "development.repository_changes.head"
  "development.repository_changes.upstream"
  "development.repository_changes.main_target"
  "development.repository_changes.detached"
  "development.repository_changes.staged_count"
  "development.repository_changes.unstaged_count"
  "development.repository_changes.untracked_count"
  "development.repository_changes.ahead"
  "development.repository_changes.behind"
  "development.repository_changes.worktree_count"
  "development.repository_changes.changed_role_counts"
  "development.repository_changes.safe_changed_file_samples[]"
  "development.repository_changes.stale_reason"
  "development.repository_development"
  "development.repository_development.current_phase"
  "development.repository_development.phase_order"
  "development.repository_development.inference_reason"
  "development.repository_development.purpose"
  "development.repository_development.required_inputs"
  "development.repository_development.allowed_writes"
  "development.repository_development.recommended_checks"
  "development.repository_development.required_checks"
  "development.repository_development.git_ci_expectations"
  "development.repository_development.required_approvals"
  "development.repository_development.cleanup_behavior"
  "development.repository_development.stop_conditions"
  "development.repository_development.runner_records_status"
  "development.repository_development.source_files[]"
  "development.workflow_evidence_events[]"
  "development.workflow_evidence_events[].event_id"
  "development.workflow_evidence_events[].source_id"
  "development.workflow_evidence_events[].observed_at"
  "development.workflow_evidence_events[].repository_head"
  "development.workflow_evidence_events[].status"
  "development.workflow_evidence_events[].freshness_state"
  "development.workflow_evidence_events[].authority"
  "development.workflow_evidence_events[].detail_artifact_path"
  "development.workflow_evidence_events[].summary"
  "development.ci_evidence[]"
  "development.ci_evidence[].role"
  "development.ci_evidence[].status"
  "development.ci_evidence[].source_id"
  "development.ci_evidence[].head_match_status"
  "development.ci_evidence[].authority"
  "development.ci_evidence[].freshness_state"
  "development.ci_evidence[].summary"
  "development.ci_evidence[].observed_at"
  "development.product_authority"
  "development.product_authority.status"
  "development.product_authority.repository.status"
  "development.product_authority.repository.configured_name"
  "development.product_authority.repository.blocker_scope"
  "development.product_authority.product_summary"
  "development.product_authority.product_summary.status"
  "development.product_authority.product_summary.name"
  "development.product_authority.product_summary.display_name"
  "development.product_authority.product_summary.display_name.ja"
  "development.product_authority.product_summary.display_name.en"
  "development.product_authority.product_summary.description"
  "development.product_authority.product_summary.source_documents"
  "development.product_authority.product_summary.source_path"
  "development.product_authority.manifest_summary"
  "development.product_authority.manifest_summary.required_missing"
  "development.product_authority.manifest_summary.optional_missing"
  "development.product_authority.evidence_summary"
  "development.product_authority.evidence_summary.items[].source_id"
  "development.product_authority.evidence_summary.items[].context"
  "development.product_authority.evidence_summary.items[].status"
  "development.product_authority.evidence_summary.items[].freshness_state"
  "development.product_authority.evidence_summary.items[].authority"
  "development.product_authority.evidence_summary.items[].required_in_context"
  "development.product_authority.evidence_summary.items[].observed_at"
  "development.product_authority.evidence_summary.items[].max_age_seconds"
  "development.product_authority.evidence_summary.items[].product_root"
  "development.product_authority.evidence_summary.items[].product_head"
  "development.product_authority.evidence_summary.items[].source_artifacts"
  "development.product_authority.evidence_summary.items[].blocked_by"
  "development.product_authority.evidence_summary.items[].next_command"
  "development.product_authority.evidence_summary.items[].detail_code"
  "development.product_authority.evidence_summary.items[].current_item_id"
  "development.product_authority.evidence_summary.items[].detail_manifest_source"
  "development.product_authority.evidence_summary.items[].detail_artifact_path"
  "development.product_authority.evidence_summary.items[].summary"
  "development.product_authority.evidence_summary.items[].reason"
  "development.product_authority.evidence_summary.items[].next_action"
  "development.product_authority.evidence_summary.items[].risk_level"
  "development.product_authority.product_operation_blockers"
  "development.product_authority.product_operation_blockers[].source"
  "development.product_authority.product_operation_blockers[].status"
  "development.product_authority.product_operation_blockers[].required_command"
  "design_studio"
  "design_studio.template_library"
  "design_studio.template_library.sync_id"
  "design_studio.template_library.registry.path"
  "design_studio.template_library.template_count"
  "design_studio.template_library.ready_count"
  "design_studio.template_library.templates[]"
  "design_studio.template_library.templates[].template_id"
  "design_studio.template_library.templates[].template_digest"
  "design_studio.template_library.templates[].required_checks[]"
  "design_studio.template_library.latest_preview"
  "design_studio.template_library.latest_preview.schema_id"
  "design_studio.template_library.latest_preview.template_proposal_id"
  "design_studio.template_library.latest_preview.candidate_operation_count"
  "design_studio.template_library.latest_preview.candidate_operations[]"
  "design_studio.template_library.latest_preview.check_plan[]"
  "design_studio.template_library.latest_preview.decision_gate.status"
  "design_studio.template_library.latest_preview.template_digest"
  "design_studio.template_library.latest_preview.proposal_only"
  "design_studio.template_library.proposal_only"
  "design_studio.subscription_agent_handoff"
  "design_studio.subscription_agent_handoff.provider_mode"
  "design_studio.subscription_agent_handoff.intent_digest"
  "design_studio.subscription_agent_handoff.response_contracts[]"
  "design_studio.subscription_agent_handoff.import_commands[]"
  "design_studio.subscription_agent_handoff.package_command"
  "design_studio.subscription_agent_handoff.package"
  "design_studio.subscription_agent_handoff.package.package_status"
  "design_studio.subscription_agent_handoff.package.package_path"
  "design_studio.subscription_agent_handoff.package.package_digest"
  "design_studio.subscription_agent_handoff.background_execution"
  "design_studio.subscription_agent_handoff.credential_storage"
  "design_studio.subscription_agent_handoff.browser_command_execution"
  "design_studio.subscription_agent_handoff.raw_prompt_included"
  "design_studio.subscription_agent_handoff.package_uploaded"
  "browser_debug"
  "browser_debug.schema_version"
  "browser_debug.status"
  "browser_debug.target"
  "browser_debug.selected_cli_repository"
  "browser_debug.tool"
  "browser_debug.tool.status"
  "browser_debug.tool.command"
  "browser_debug.tool.source"
  "browser_debug.manifest"
  "browser_debug.manifest.status"
  "browser_debug.manifest.path"
  "browser_debug.manifest.command"
  "browser_debug.review"
  "browser_debug.review.status"
  "browser_debug.review.artifact_index_path"
  "browser_debug.review.command"
  "browser_debug.agent_package"
  "browser_debug.agent_package.status"
  "browser_debug.agent_package.path"
  "browser_debug.agent_package.command"
  "browser_debug.agent_result"
  "browser_debug.agent_result.status"
  "browser_debug.agent_result.path"
  "browser_debug.agent_result.command"
  "browser_debug.agent_report"
  "browser_debug.agent_report.status"
  "browser_debug.agent_report.path"
  "browser_debug.agent_report.command"
  "browser_debug.boundary"
  "browser_debug.boundary.dashboard_executes_browser_debug"
  "browser_debug.boundary.external_upload"
  "browser_debug.boundary.provider_api"
  "browser_debug.boundary.credential_storage"
  "browser_debug.boundary.product_repository_mutated"
  "operational_decision"
  "operational_decision.status"
  "operational_decision.decision_question"
  "operational_decision.primary_blocker_source_id"
  "operational_decision.why_blocked"
  "operational_decision.next_safe_action"
  "operational_decision.done_condition"
  "operational_decision.approval_boundary"
  "operational_decision.risk_level"
  "operational_decision.freshness_state"
  "operational_decision.authority"
  "operational_decision.source_id"
  "operational_decision.audience_briefs.non_engineer"
  "operational_decision.audience_briefs.junior_engineer"
  "operational_decision.command_execution_mode"
  "decision_pages[]"
  "decision_pages[].id"
  "decision_pages[].title"
  "decision_pages[].scope"
  "decision_pages[].audiences[]"
  "decision_pages[].status"
  "decision_pages[].decision_question"
  "decision_pages[].decision_question_key"
  "decision_pages[].current_judgment"
  "decision_pages[].current_judgment_key"
  "decision_pages[].top_reason"
  "decision_pages[].top_reason_key"
  "decision_pages[].evidence_confidence"
  "decision_pages[].evidence_confidence_key"
  "decision_pages[].must_review[]"
  "decision_pages[].must_review_keys[]"
  "decision_pages[].next_safe_action"
  "decision_pages[].next_safe_action_key"
  "decision_pages[].detail_page"
  "decision_pages[].owner_source"
  "decision_pages[].source_id"
  "decision_pages[].authority"
  "decision_pages[].freshness_state"
  "decision_pages[].risk_level"
  "decision_pages[].command_execution_mode"
  "maintenance.as_built_sync_status"
  "maintenance.workflow_pair_status"
  "maintenance.developer_memory_status"
  "maintenance.skills_status"
  "maintenance.evidence_rows[]"
  "maintenance.evidence_rows[].id"
  "maintenance.evidence_rows[].label"
  "maintenance.evidence_rows[].importance"
  "maintenance.evidence_rows[].status"
  "maintenance.evidence_rows[].reference"
  "git_workflow.policy_status"
  "git_workflow.settings_status"
  "git_workflow.gate_status"
  "git_workflow.approval_status"
  "security.policy_status"
  "security.gate_status"
  "security.dangerous_action_approval"
  "security.approvals[]"
  "security.approvals[].id"
  "security.approvals[].label"
  "security.approvals[].status"
  "security.approvals[].detail"
  "security.approvals[].last_checked"
  "security.dangerous_operations[]"
  "security.dangerous_operations[].id"
  "security.dangerous_operations[].label"
  "security.dangerous_operations[].status"
  "security.dangerous_operations[].detail"
  "security.dangerous_operations[].last_checked"
  "actions.command_previews[].intent"
  "actions.command_previews[].target"
  "actions.command_previews[].risk_level"
  "actions.command_previews[].requires_approval"
  "actions.command_previews[].approval_gate_id"
  "actions.command_previews[].argv"
  "actions.command_previews[].command_text"
  "actions.command_previews[].execution_mode"
  "actions.command_previews[].non_executable"
  "actions.command_preview_groups[]"
  "actions.command_preview_groups[].id"
  "actions.command_preview_groups[].label"
  "actions.command_preview_groups[].risk_level"
  "actions.command_preview_groups[].preview_count"
)

for path in "${required_paths[@]}"; do
  require_path "$path"
done

require_enum_contains "git_workflow.policy_status" "ready"
require_enum_contains "git_workflow.gate_status" "passed"
require_enum_contains "git_workflow.approval_status" "approval_required"
require_enum_contains "security.policy_status" "ready"
require_enum_contains "security.gate_status" "passed"
require_enum_contains "security.dangerous_action_approval" "approval_required"
require_enum_contains "summary.mode" "unknown"
require_enum_contains "summary.ui_locale" "ja"
require_enum_contains "summary.ui_locale" "en"
require_enum_contains "summary.ui_locale" "ko"
require_enum_contains "summary.ui_locale" "zh-CN"
require_enum_contains "summary.ui_locale" "zh-TW"
require_enum_contains "summary.ui_locale" "es"
require_enum_contains "summary.ui_locale" "pt-BR"
require_enum_contains "summary.ui_locale" "fr"
require_enum_contains "summary.ui_locale" "de"
require_enum_contains "summary.ui_locale" "id"
require_enum_contains "summary.ui_locale" "vi"
require_enum_contains "summary.ui_locale" "th"
require_enum_contains "summary.ui_locale" "hi"
require_enum_contains "summary.ui_locale" "ar"
require_enum_contains "summary.ui_direction" "ltr"
require_enum_contains "summary.ui_direction" "rtl"
require_enum_contains "selected_context.menu_id" "step_1_14"
require_enum_contains "selected_context.workflow_context" "free-development"
require_enum_contains "selected_context.git_status" "not_run"
require_enum_contains "selected_context.ci_status" "manual_required"
require_enum_contains "selected_context.security_status" "blocked"
require_enum_contains "development.git_operations[].status" "approval_required"
require_enum_contains "operational_decision.status" "manual_required"
require_enum_contains "operational_decision.risk_level" "critical"
require_enum_contains "operational_decision.freshness_state" "stale"
require_enum_contains "operational_decision.authority" "manual_required"
require_enum_contains "operational_decision.command_execution_mode" "preview_only"
require_enum_contains "decision_pages[].id" "overview"
require_enum_contains "decision_pages[].id" "repository-info"
require_enum_contains "decision_pages[].id" "history"
require_enum_contains "decision_pages[].audiences[]" "non_engineer"
require_enum_contains "decision_pages[].audiences[]" "junior_engineer"
require_enum_contains "decision_pages[].detail_page" "#repository-info"
require_enum_contains "decision_pages[].owner_source" "repository-development-workflow"
require_enum_contains "decision_pages[].command_execution_mode" "preview_only"
require_enum_contains "development.repository_changes.status" "manual_required"
require_enum_contains "development.repository_changes.path_state" "configured"
require_enum_contains "development.repository_changes.git_state" "configured"
require_enum_contains "development.repository_development.current_phase" "fast_loop"
require_enum_contains "development.repository_development.current_phase" "release_gate"
require_enum_contains "development.repository_development.runner_records_status" "current"
require_enum_contains "development.workflow_evidence_events[].status" "stale"
require_enum_contains "development.workflow_evidence_events[].freshness_state" "not_collected"
require_enum_contains "development.workflow_evidence_events[].authority" "advisory"
require_enum_contains "development.ci_evidence[].role" "branch_ci"
require_enum_contains "development.ci_evidence[].role" "provider_visibility"
require_enum_contains "development.ci_evidence[].head_match_status" "unknown"
require_enum_contains "documents.status" "ready"
require_enum_contains "documents.catalog[].status" "manual_required"
require_enum_contains "documents.catalog[].audience" "all"
require_enum_contains "documents.catalog[].related_page" "#maintenance"
require_enum_contains "settings.status" "approval_required"
require_enum_contains "settings.items[].scope" "workflow"
require_enum_contains "settings.items[].related_page" "#settings"
require_enum_contains "maintenance.evidence_rows[].status" "stale"
require_enum_contains "design_studio.template_library.latest_preview.schema_id" "TemplateProposal"
require_enum_contains "design_studio.template_library.latest_preview.decision_gate.status" "manual_required"
require_enum_contains "design_studio.subscription_agent_handoff.provider_mode" "subscription-agent"
require_enum_contains "design_studio.subscription_agent_handoff.package.package_status" "ready"
require_enum_contains "browser_debug.status" "optional"
require_enum_contains "browser_debug.status" "not_run"
require_enum_contains "browser_debug.status" "manual_required"
require_enum_contains "browser_debug.status" "passed"
require_enum_contains "browser_debug.tool.status" "manual_required"
require_enum_contains "browser_debug.manifest.status" "ready"
require_enum_contains "browser_debug.review.status" "not_run"
require_enum_contains "browser_debug.agent_package.status" "not_run"
require_enum_contains "browser_debug.agent_result.status" "not_run"
require_enum_contains "browser_debug.agent_report.status" "not_run"
require_enum_contains "security.approvals[].status" "approval_required"
require_enum_contains "security.dangerous_operations[].status" "blocked"
require_enum_contains "available_contexts[].status" "ready"
require_enum_contains "summary.guidance_items[].surface" "lesson"
require_enum_contains "summary.guidance_items[].surface" "workflow"
require_enum_contains "summary.guidance_items[].audience" "non_engineer"
require_enum_contains "summary.guidance_items[].audience" "engineer"
require_enum_contains "summary.guidance_items[].priority" "attention"
require_enum_contains "summary.primary_action.risk_level" "low"
require_enum_contains "summary.primary_action.status" "approval_required"
require_enum_contains "summary.category_metrics.*.status" "ready"
require_enum_contains "summary.manual_followups[].status" "optional"
require_enum_contains "development.product_authority.status" "not_run"
require_enum_contains "development.product_authority.status" "stale"
require_enum_contains "development.product_authority.repository.blocker_scope" "product_operations"
require_enum_contains "development.product_authority.product_summary.status" "ready"
require_enum_contains "development.product_authority.product_summary.status" "missing"
require_enum_contains "development.product_authority.evidence_summary.items[].status" "not_run"
require_enum_contains "development.product_authority.evidence_summary.items[].status" "stale"
require_enum_contains "development.product_authority.evidence_summary.items[].status" "manual_required"
require_enum_contains "development.product_authority.evidence_summary.items[].status" "not_applicable"
require_enum_contains "development.product_authority.evidence_summary.items[].freshness_state" "not_collected"
require_enum_contains "development.product_authority.evidence_summary.items[].authority" "not_collected"
require_enum_contains "development.product_authority.evidence_summary.items[].risk_level" "critical"
for product_evidence_detail_path in \
  "development.product_authority.evidence_summary.items[].context" \
  "development.product_authority.evidence_summary.items[].required_in_context" \
  "development.product_authority.evidence_summary.items[].observed_at" \
  "development.product_authority.evidence_summary.items[].max_age_seconds" \
  "development.product_authority.evidence_summary.items[].product_root" \
  "development.product_authority.evidence_summary.items[].product_head" \
  "development.product_authority.evidence_summary.items[].source_artifacts" \
  "development.product_authority.evidence_summary.items[].blocked_by" \
  "development.product_authority.evidence_summary.items[].next_command" \
  "development.product_authority.evidence_summary.items[].detail_code" \
  "development.product_authority.evidence_summary.items[].current_item_id" \
  "development.product_authority.evidence_summary.items[].detail_manifest_source" \
  "development.product_authority.evidence_summary.items[].detail_artifact_path" \
  "development.product_authority.evidence_summary.items[].summary" \
  "development.product_authority.evidence_summary.items[].reason" \
  "development.product_authority.evidence_summary.items[].next_action" \
  "development.product_authority.evidence_summary.items[].risk_level"; do
  require_implemented_status "$product_evidence_detail_path"
done
require_enum_contains "development.product_authority.product_operation_blockers[].status" "not_run"
require_enum_contains "development.product_authority.product_operation_blockers[].status" "stale"
require_enum_contains "live_status.menu_id" "free-development"
require_enum_contains "live_status.workflow_context" "external-integration"
require_enum_contains "live_status.checks.*.status" "manual_required"
require_enum_contains "live_status.checks.*.detail_page" "#workflow"
require_enum_contains "live_status.checks.*.detail_page" "#safety"
require_enum_contains "live_status.checks.*.freshness_state" "not_collected"
require_enum_contains "live_status.checks.*.authority" "manual_required"
require_enum_contains "live_status.checks.*.risk_level" "critical"
require_enum_contains "live_status.checks.*.items[].status" "failed"
require_enum_contains "live_status.checks.*.items[].freshness_state" "stale"
require_enum_contains "live_status.checks.*.items[].authority" "not_collected"
require_enum_contains "live_status.checks.ci.head_match_status" "matched"
require_enum_contains "live_status.checks.ci.head_match_status" "different"
require_enum_contains "actions.command_previews[].execution_mode" "preview_only"
require_enum_contains "actions.command_preview_groups[].risk_level" "critical"

if ! awk -F '\t' '$1 !~ /^#/ && $2 == "source_files" && $5 == "relative-path-list" { found = 1 } END { exit found ? 0 : 1 }' "$SCHEMA"; then
  report "source_files must use relative-path-list"
fi

if ! awk -F '\t' '$1 !~ /^#/ && $2 == "actions.command_previews[].non_executable" && $5 == "true" { found = 1 } END { exit found ? 0 : 1 }' "$SCHEMA"; then
  report "command previews must be explicitly non-executable"
fi

if [[ $missing -ne 0 ]]; then
  printf '\nDashboard schema test failed.\n' >&2
  exit 1
fi

printf 'Dashboard schema test passed.\n'
